### PR TITLE
add feature to control relation generation

### PR DESCRIPTION
**Pull request by lekoala**
add a reference to root DataObject. This allow to track the level of nesting.
we add two configuration options: setAddRelations (enable/disable globally) and setAddNestedRelations (set to false to only allow on root object)

### CODE REVIEW

**Review by chrispenny — CHANGES_REQUESTED** [review]
Thank you for the submission! I can see the value in allowing you to control the depth of relationships that you add.

One issue I see with this approach is that we don't necessarily only have 1 root `DataObject`. The intent is for you to be able to add many "root" `DataObjects` using the service before you output the complete fixture.

EG:
```
$service = new FixtureService();
$service->addDataObject($pageOne);
$service->addDataObject($pageTwo);
// etc

$service->outputFixture();
```

In this case, the Service would have the root `DataObject` set from my first `addDataObject` call, and `$pageTwo` would get treated as `!$this->rootDataObject`.

The other (kind of) issue, is that you are limited to specific set of depth controls (allowed depth: 1, 2, or 3).

I think this might be better controlled by adding some form of `$depth` integer tracking.

```
private $allowedDepth;

public function addDataObject(DataObject $dataObject, int $currentDepth = 0): FixtureService
{
  ...

  $currentDepth += 1;

  // If the DataObject has Fluent applied, then we also need to add Localised fields.
  if ($dataObject->hasExtension(FluentExtension::class)) {
    // addDataObjectLocalisedFields() will need similar depth tracking checks added.
    $this->addDataObjectLocalisedFields($dataObject, $currentDepth);
  }

  if ($currentDepth >= $this->getAllowedDepth()) {
    return;
  }

  // Add direct relationships.
  $this->addDataObjectHasOneFields($dataObject, $currentDepth);
  // Add belongs to relationships.
  $this->addDataObjectBelongsToFields($dataObject, $currentDepth);
  // has_many fields will include any relationships that you're created using many_many "through".
  $this->addDataObjectHasManyFields($dataObject, $currentDepth);
  // many_many relationships without a "through" object are not supported. Add warning for any relationships
  // we find like that.
  $this->addDataObjectManyManyFieldWarnings($dataObject, $currentDepth);
}

...

// $allowedDepth getter, setter
```

The methods that add relationships will all need to be sure to pass their `$currentDepth` back to `addDataObject()` whenerver they call it.

Usage:
```
$service = new FixtureService();
$service->setAllowedDepth(1);
$service->addDataObject($pageOne);
$service->addDataObject($pageTwo);
// etc

$service->outputFixture();
```

I'd be happy to look into this a bit more **hopefully** later this week, but please feel free to update your PR if you have time available 😃 .

**Comment by lekoala** [comment]
yes it's probably better to use a depth parameter. I got confused at some point try to track "global" depth but that doesn't make any sense it's much better to use a local var and pass it along. I can give it a try :-) my goal is to be able to generate fixtures for objects that would otherwise output gigantic yml in order to use them in unit tests. in that regard, your module worked really well for me!

**Comment by chrispenny** [comment]
Awesome! I was very happy to see your PRs. To be honest I didn't think anyone else was using this module haha. This has given me some new enthusiasm.

Please feel free to push up any new changes, and/or add any comments. I'm more than happy to provide guidance. If at any time you would like to "pass the torch" then I can pick it up - but I don't want to just remove the learning experience 😃

**Comment by lekoala** [comment]
you can have a look at https://github.com/chrispenny/silverstripe-data-object-to-fixture/pull/6
by default, it's nullable so it behaves as before. it you set allowedDepth = 0, then it means there is no relation generated. it thought it was probably better than having "1" as the base value, but we could also make it a pure int and start with 1 being no relations

**Comment by chrispenny** [comment]
Thanks, @lekoala! I hope to have some time available to check this out on Friday NZT.

**Comment by chrispenny** [comment]
Delivered as part of #6

**Pull request closed without merging**
